Global:
  output: ./outputs
  num_iter: 1000
  device: [0]

Arch:
  input_dims: [240, 76, 216, 47, 64, 6]
  hidden_dims: [300, 300, 300, 300, 300, 300]
  output_dims: [128, 128, 128, 128, 128]
  num_class: 10
  fusion_method: equal

Data:
  Dataset:
    name: HandWritten
    data_root: ./data/paperdata/handwritten.mat
    test_size: 0.2
    random_state: 1

  DataLoader:
    batch_size: 1000