Global:
  output: ./outputs/handwritten
  num_iter: 1000
  device: [0]
  epochs: 100
  dim: &dim 128

Arch:
  input_dims: [240, 76, 216, 47, 64, 6]
  hidden_dims: [300, 300, 300, 300, 300, 300]
  output_dims: [*dim, *dim, *dim, *dim, *dim]
  num_class: 10
  fusion_method: caf
  tau: 1

Data:
  Dataset:
    name: HandWritten
    data_root: ./data/paperdata/handwritten.mat
    test_size: 0.2
    random_state: 1

  DataLoader:
    batch_size: 1000

Loss:
  CELoss:
    weight: 1.

Metric:
  Accuracy:
    weight: 1
  