Global:
  output: ./outputs/landUse21
  num_iter: 1000
  device: [0]
  epochs: 100
  dim: &dim 128

Arch:
  input_dims: [20, 59, 40]
  hidden_dims: [300, 300, 300]
  output_dims: [*dim, *dim, *dim]
  num_class: 21
  fusion_method: equal
  tau: 1

Data:
  Dataset:
    name: Scene15
    data_root: ./data/paperdata/LandUse-21.mat
    test_size: 0.2
    random_state: 1

  DataLoader:
    batch_size: 1000

Loss:
  CELoss:
    weight: 1.

Metric:
  Accuracy:
    weight: 1
  
