Global:
  output: ./outputs/scene15
  num_iter: 1000
  device: [0]
  epochs: 100

Arch:
  input_dims: [20, 59, 40]
  hidden_dims: [300, 300, 300]
  output_dims: [128, 128, 128]
  num_class: 15
  fusion_method: caf
  tau: 1

Data:
  Dataset:
    name: Scene15
    data_root: ./data/paperdata/Scene-15.mat
    test_size: 0.2
    random_state: 1

  DataLoader:
    batch_size: 1000

Loss:
  CELoss:
    weight: 1.

Metric:
  Accuracy:
    weight: 1
  